apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}
data:
  application.properties: |
    #AMQP
    queue.management-url={{ default "none" .Values.amqp.managementUrl }}
    queue.host={{ .Values.amqp.host }}
    queue.username=${rabbitmq-username}
    queue.password=${rabbitmq-password}
    queue.port={{ .Values.amqp.port }}
    queue.connectionTimeout={{ .Values.amqp.connectionTimeout }}
    queue.ssl.enabled={{ .Values.amqp.sslEnabled }}
    queue.ssl.key-store={{ .Values.amqp.sslKeyStore }}
    queue.ssl.key-store-type={{ .Values.amqp.sslKeyStoreType }}
    queue.ssl.protocol={{ .Values.amqp.sslProtocol }}
    queue.ssl.key-store-password={{ .Values.amqp.sslKeyStorePassword }}

    worker.deployment.label={{ .Values.worker.deploymentLabel }}
    autoscale.monitoring.rate={{ .Values.autoscale.monitoringRate }}

    {{- if .Values.extraConfig }}
    {{ .Values.extraConfig | indent 4 | trim }}
    {{- end }}
