---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}
  labels:
    app: amqp-pod-autoscaler
    chart: {{ template "amqp-pod-autoscaler.chart" . }}
    release: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}-deployment-updater
  labels:
    app: amqp-pod-autoscaler
    chart: {{ template "amqp-pod-autoscaler.chart" . }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "deployments/scale", "deployments/status", "replicasets", "replicsets/scale", "replicasets/status"]
    verbs: ["get", "update", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}-update-deployments
  labels:
    app: amqp-pod-autoscaler
    chart: {{ template "amqp-pod-autoscaler.chart" . }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "amqp-pod-autoscaler.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "amqp-pod-autoscaler.fullname" . }}-deployment-updater
  apiGroup: rbac.authorization.k8s.io
