{{- if not .Values.existingAutoscalerSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}
  labels:
    app: amqp-pod-autoscaler
    chart: {{ template "amqp-pod-autoscaler.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if not .Values.existingRabbitSecret }}
  rabbitmq-username: {{ (toString .Values.amqp.username) | b64enc }}
  rabbitmq-password: {{ (toString .Values.amqp.password) | b64enc }}
  {{- end }}
{{- end }}
